name: yarab
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^7.1.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  http: ^0.13.6
  injectable: ^2.1.1
  lint: any

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  injectable_generator: any
  auto_route_generator: any

flutter:
  uses-material-design: true
